AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc']
  IgnoredMethods: ['describe', 'context']
  Max: 20

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude: ['**/*.rake']

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
