name: Main

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'development'
      CC_TEST_REPORTER_ID: '640d490defec165928507980a40f2eec5bbc84a85b79018af7e5e618481c74be'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Run RuboCop 🚓
      run: |
        bundle exec rake rubocop

    - name: Setup DB 🗄️
      run: |
        bundle exec rails db:setup

    - name: Run Tests ✅
      run: |
        bundle exec rake spec

    - name: Report Coverage
      uses: paambaati/codeclimate-action@v2.7.5
