name: Main 🔧

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_WITHOUT: 'development'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Setup DB 🗄️
      run: |
        bundle exec rails db:setup

    - name: Run Tests ✅
      run: |
        bundle exec rake spec

    - name: Run RuboCop 🚓
      run: |
        bundle exec rake rubocop
