name: Main

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'development'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Setup DB 🗄️
      run: |
        bundle exec rails db:setup

    - name: Run Tests ✅
      run: |
        bundle exec rake spec

    - name: Run RuboCop 🚓
      run: |
        bundle exec rake rubocop
