name: Main

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'development'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Setup DB 🗄️
      run: |
        bundle exec rails db:setup

    - name: Run Tests ✅
      run: |
        bundle exec rake spec

    - name: Run RuboCop 🚓
      run: |
        bundle exec rake rubocop

    - name: Report Coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        # Coverage is already generated in test step, need to run anything again
        coverageCommand: echo '' > /dev/null
