name: pre-release

on:
  pull_request:
    types: [ labeled ]
    branches: [main]

jobs:
  pre-release:
    if: ${{ github.event.label.name == "autorelease:\ tagged" }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: 'development'

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install Packages
        uses: bahmutov/npm-install@v1

      - name: Run Bundle Install
        run: bundle

      - name: Bump Version
        run: |
          version=$(cat lib/rails_mini_profiler/version.rb | grep VERSION | cut -d'"' -f2)
          npm version --no-git-tag-version $version

      - name: Commit Files
        uses: EndBug/add-and-commit@v7
        with:
          add: "['Gemfile.lock', 'package.json', 'package-lock.json']"
          message: "chore: bump npm version to ${{ needs.prepare-release.outputs.version }}"
